### PR TITLE
Expose the serialisation blocker sentinel object.

### PR DESCRIPTION
**Pull request by mikehearn**

### CODE REVIEW

**Comment by pron** [comment]
I don't know how I feel about this at this early stage of fiber-serialization use. Those brave souls playing with new use-cases can just get the object using reflection for now. I'm not sure we should commit to an API change (and a public field is an API) at this time.

**Comment by mikehearn** [comment]
Quasar is a <1.0 product, I didn't realise the API was meant to be fully stabilised.

You could consider using the Guava @Beta annotation, as a middle path.

**Comment by pron** [comment]
It is not fully stabilized, but I'd rather not add a new API until we better understand how it can be used. For example, it is possible that it is sufficient to add -- in addition to `parkAndSerialize` another `snapshot` method. Or, if a more general usage is required, it might be better to add something less crude than a specific blocker.

Again -- it's not so much about making breaking changes as introducing API churn before the use-cases are understood, especially as there are acceptable temporary workarounds.

**Comment by mikehearn** [comment]
Yes, fair enough. It'd be an ugly API for sure, a snapshot method would work better.

**Pull request closed without merging**
